site_name: "Оникс: Краткая Энциклопедия"
site_url: https://eternaldrifter.github.io/onyx/
site_description: Лор, карты и всякая хуйня
site_author: Мохарий Сет

theme:
  name: material
  features:
    - palette.toggle
  palette:
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/weather-sunny
        name: День
    - scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-night
        name: Ночь

nav:
  - Главная: index.md
  # Календарь: calendar.md 
  - Лор:
      - География: lore/geograph.md
      - Общий лор: lore/lore.md
      - Хронология: lore/time.md
      - Государства: lore/countryis.md
      - Организции: lore/orgs.md
      - Локации: lore/locations.md
      - Боги: lore/gods.md
      
  - Свободные города: indeptowns.md
  - Веймария: veym.md

extra_css:  
 - css/extra.css

markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences
 - pymdownx.tilde
 - pymdownx.inlinehilite
 - pymdownx.emoji
 - pymdownx.caret
 - attr_list
 - tables
 - footnotes
 - toc
